apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::726065578311:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1N3X1F4EP6XJF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::726065578311:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-26T07:00:38Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1472"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: ccdfa86c-b731-45dd-9fff-ae72ef3da5e7
