apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::613461101071:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1Q679NG5U32ZK
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-02-19T05:50:26Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1493"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: c88fab2e-5ba9-4a44-bbb1-64ba4561290d
