apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::726065578311:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-MXP7B7T3E3NT
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::726065578311:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-09-28T13:09:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1534"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 6904aad5-9a7a-449d-8371-49bbd24a90b8
